AlexGuillard/Area

- .github/workflows/checks.yml
Add verification of server's linter and server's tests only on PR
> ci: add check for server's linter and server's tests

- server/src/app.module.ts
- server/src/auth/auth.controller.spec.ts
- server/src/auth/auth.controller.ts
- server/src/auth/auth.module.ts
- server/src/auth/auth.service.spec.ts
- server/src/auth/auth.service.ts
- server/src/auth/dto/auth.dto.ts
- server/src/auth/dto/index.ts
close #13 
this routes require a body with a mail and a password
don't do anything if the body is correct
you can check this feature on the swagger in http://localhost:8080/api
> feat(server): empty route signin/signup

- .github/workflows/checks.yml
- web/package.json
> ci(web): add linter check

- server/prisma/migrations/20231215142546_db/migration.sql
- server/prisma/schema.prisma
- server/src/app.module.ts
- server/src/auth/auth.service.ts
- server/src/auth/dto/auth.dto.ts
- server/src/me/dto/index.ts
- server/src/me/dto/me.dto.ts
- server/src/me/me.controller.ts
- server/src/me/me.module.ts
- server/src/me/me.service.spec.ts
- server/src/me/me.service.ts
- close #12 
- need to specify token of user in route
- return id and mail of user
> feat(12 > main): setup me route

- .github/workflows/checks.yml
> ci(mobile): add linter check

- server/src/auth/auth.controller.ts
- server/src/auth/dto/index.ts
- server/src/auth/dto/token.dto.ts
- correct arguments on back for better parse
- add example for swagger
> fix(google-params > main): change arguments login google

- mobile/Dockerfile
- mobile/android/app/build.gradle
> feat(mobile): make apk release

- web/src/Component/GoogleButton/GoogleButton.tsx
- web/src/Page/Register/register.tsx
Closes #56 
add google button on register page like that
> feat(GoogleService (56 > main)): add GoogleButton to register

- README.md
- docker-compose.yml
> feat(docker compose): add pgAdmin service

- .github/workflows/codecov.yml
- codecov.yml
- server/package.json
> ci(codecov): add codecov job

- .github/workflows/apk_check.yml
- .github/workflows/checks.yml
> ci(core): add server, web and apk build execution

- .github/workflows/apk_check.yml
- .github/workflows/checks.yml
Linked to:
- #3 
And this PR should be already in main, but we merged her in wrong branch (dev) [here](https://github.com/AlexGuillard/Area/pull/67).
> ci(core): add server, web and apk build execution 

- .github/workflows/checks.yml
- docker-compose.prod.yml
- web/package-lock.json
- web/src/App.tsx
- web/src/Component/Add/add.tsx
- web/src/Component/Edit/edit.tsx
- web/src/Component/ServiceCard/serviceCard.tsx
- web/src/Page/Area/area.tsx
- web/src/Page/Login/login.tsx
- web/src/Page/Register/register.tsx
- web/src/Page/Services/services.tsx
> refactor(web): remove all warning web site

- web/pnpm-lock.yaml
- web/src/Component/Add/add.css
- web/src/Component/Add/add.tsx
- web/src/Page/Area/area.css
- web/src/Page/Login/login.css
- web/src/Page/Register/register.css
- web/src/Page/Services/services.css
> style(web): add better cursor on clickable element

- server/src/reaction/mailing/mailing.service.ts
> fix(GoogleService): check the enum GOOGLE to catch the random token

- server/src/area/area.controller.ts
- server/src/area/area.service.ts
- close #96 
- change specific area
- need in param token of user, id of area and same body as a POST area
> feat(server): area PUT

- web/src/Component/ServiceCard/serviceCard.css
- web/src/Component/ServiceCard/serviceCard.tsx
> feat(web): add mouse hover on cards

- web/src/Component/Add/add.tsx
- web/src/Page/Area/area.tsx
> fix(web): update page, when adding a new area

- server/src/reaction/spotify/spotify.service.ts
Closes #190 
fix console logs + emitter for spotify's reactions
> Fix:(190 > main): fix add all eventemitter for spotify actions

- server/src/about/about.service.ts
- server/src/action/time/dto/time.dto.ts
- server/src/action/time/time.service.ts
new time action
trigger the reaction every time couldown finish
> feat: couldown action time

- deployement/playbooks/playbook.yml
- mobile/Dockerfile.prod
Linked to no issue.
It allow to set ip / port of mobile prod correctly for deployement
> feat(deployement): add env var in dockerfile of mobile prod 

- mobile/src/components/addComponent.tsx
- mobile/src/pages/AreaPage.tsx
Fixed some display issues:
- area list to hight on the page
- action list behind reaction button
- reaction list behind create button
> refactor(mobile): fix display issues in AreaPage

- server/src/action/openweather/openweather.service.ts
Closes #214 
fix the wrong arg i gave
> fix(Weather): :ambulance: change actionId by weather struct

- server/src/about/about.service.ts
- server/src/reaction/spotify/spotify.service.ts
> 216 feat spotify reaction premium
